# Generated by Django 4.1.4 on 2023-04-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['subject__name', 'semester']},
        ),
    ]
