# Generated by Django 4.1.4 on 2023-04-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='building',
            field=models.CharField(blank=True, choices=[['A', 'A'], ['B', 'B'], ['C', 'C'], ['D', 'D']], default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
